### ISSUE TITLE
Data storage

### ISSUE THREAD

**Issue by PedroVelez** [euroargodev/argoonlineschool#1]
@gmaze I am using this web address Options https://www.oceanografia.es/argoonlineschool/Data/ to avoid uploading the data used in the AoS to github . I think there is a more elegant way of doing, any idea?

**Comment by PedroVelez** [comment]
@quai20 any suggestion?

**Comment by quai20** [comment]
Hi @PedroVelez 
Sorry for my late response.
I think that it's important that users see how argo data is structured, so working with files and dac directory,etc ... is a good thing. You could imagine doing everything with remote access and catalog (with [intake](https://intake.readthedocs.io/en/latest/) for example) but it's better for the user to see the files I think.
Then how do you store/download the data, I think that the way you do it is good for users who uses their own jupyter/env. It's well presented in the Data section of the Jupyter-book. 
Also I see that there's a binder button in it, so If you're planning to offer a binder server to the users, you can download the data automatically while setting up the binder env.

**Comment by PedroVelez** [comment]
Finally the best option, at least for the purpose of the AoS is to use Google drive to store the content of the ./Data folder, in that way user can see the structure of the folder and download jsut one file or all of them.
