### ISSUE TITLE
typos and errors

### ISSUE THREAD

**Issue by francispoulin** [euroargodev/argoonlineschool#16]
I had a student work through your notebooks recently and she learned a lot.  Thank you for putting these together!

She did find a bunch of typos and errors, which I thought I would share with you. I presume you will want to correct them when  you have time.

[Argo Website Errors and Typos.pdf](https://github.com/user-attachments/files/16350825/Argo.Website.Errors.and.Typos.pdf)

**Comment by Alberto-GS** [comment]
> I had a student work through your notebooks recently and she learned a lot. Thank you for putting these together!
> 
> She did find a bunch of typos and errors, which I thought I would share with you. I presume you will want to correct them when you have time.
> 
> [Argo Website Errors and Typos.pdf](https://github.com/user-attachments/files/16350825/Argo.Website.Errors.and.Typos.pdf)

Thanks a lot for your feedback @francispoulin, really aprreciate it !!!

I was trying to correct typos and errors but for some reson I'm not able to do any modifications any more. Even directly here in the repository (I usually work with GitHub desktop, since I'm not an expert). My guess is there's some issue with permission or something in the repository is not working properly. I'll try to take care of it ASAP.

**Comment by PedroVelez** [comment]
> I had a student work through your notebooks recently and she learned a lot. Thank you for putting these together!
> 
> She did find a bunch of typos and errors, which I thought I would share with you. I presume you will want to correct them when you have time.
> 
> [Argo Website Errors and Typos.pdf](https://github.com/user-attachments/files/16350825/Argo.Website.Errors.and.Typos.pdf)

Thanks a lot, we are correcting all the errors and typos:

- 1. Lesson 2: The Argo Data → The 2 links at the bottom of the page (acces data by float and by date) gives a 404 error when opened. Also, there is a typo in the hyperlink (highlighted in yellow).
- [ ] Thanks, we have updated the links

- 2. Lesson 3: Using Argo Data → Data Used in the Argo Online School → wget ftp://ftp.ifremer.fr/ifremer/argo/dac/coriolis/6901254/*` has an additional apostrophe (highlighted in yellow) that causes an error when being executed. Similarly for this link wget ftp://ftp.ifremer.fr/ifremer/argo//geo/indian_ocean/2019/11/20191111_
prof.nc` below it.

- [ ] thanks!

- 3. Lesson 3: Using Argo Data → Data Used in the Argo Online School → In the text “However we recomend to download the data from here” the “here” hyperlink takes you to a Google Drive that has a blank “HowtoDownload” document. Also, there is a typo in the text highlighted in yellow.

- 4. Lesson 3: Accessing Argo Data by float → This hyperlink “Real-Time and Delayed mode data” is referenced 3 times on this page and all show a 404 error when opened. At the very bottom of the same page, “See the Data section for instructions on how to download the data” the “Data” hyperlink gives a 404 error.

- 5. Lesson 3: Reading an Argo CTD cycle data → There are a few typos in this paragraph (highlighted in yellow): “N_LEVELS is the number of vertical leves, i.e. in pressure. N_PROF the number of profiles within the cycle, as we saw previously. N_PARAM is te number of paramters, 3 for this float: TEMP, PSAL and PRES”.

- 6. Lesson 3: Accessing all Profiles at once → There are a few typos in this sentence (highlighted in yellow): “Conveniently, all the core mision profiles are compated in a single file, named:”

- 7. Lesson 3: Accessing Argo Data by Float Using Argopy → When executing this line of code, it gives an Attribute error: “argo_loader.float(6901254).load()”. Changing the src from erddap to argovis or gdac also gives different errors.

- 8. Lesson 3: Reading Argo data by Date → This hyperlink gives a 404 error when opened: “See here for instructions on how to download the data”

- 9. Lesson 3: Reading Argo data by Date → There is a typo in this sentence (highlighted in yellow): “In these files there are also the core argo variables TEMP PSAL and PRE, we can just take a quick look at the data a the most superficial level for each profile.”

- 10. Lesson 3: Reading Argo Data by Date → In the code following this statement: “To evalute the 10 dbar temperature in the last month:” the files being accessed are from 2010 whereas the graph mentions 2020. Also, there is a typo in the highlighted text.

- 11. Lesson 3: Accessing Argo Data by Date using Argopy → The argopy.plotters used in the last code of the notebook shows “Attribute Error: module 'argopy' has no attribute 'plotters’”

- 12. Lesson 3: Real time quality control data → The following text mentions 2019 but the dataset opened in the next line of code is for 2020: “QC flags for data accessed by date open the daily data set from the 11th November 2019”

- 13. Lesson 3: Real time quality control data → There are a few typos in this sentence (highlighted in yellow): “There a lot of profiles with Quality Flag (QC) that indicate bada data. Now, we will plot the same TS diagram, but color coding the data bvased on the Quality flags.”

**Comment by PedroVelez** [comment]
thanks a lot @francispoulin , and to your student. We have fixed all the errors listed. We have also improved, significantly Lesson 3, and modify is numbering to make it easier to follow.
