### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ldiaz-barroso** [euroargodev/argoonlineschool#2]
**Fallos ortográficos**
### The Argo data / The Basics of netCDF format

- Accessing a netCDF data variable

> Sustituir "We can just extract one **sigle**", por "We can just extract one **single**"

> Sustituir "It is also possible to use the attributes of a data **variblle**", por "It is also possible to use the attributes of a data **varible**"

- Using the data

> Sustituir "Let’s actually use the data, **firt**", por "Let’s actually use the data, first"

### Accesing argo data by float

- Data files organized by float

> Añadir negrita a "c" en la frase: "When accessing the dac"

### Accesing Argo data by date

- Data files organized by date

> Añadir al "(See here for isntruction of how to dowload the data)" el hipervínculo

------------------------------------------------

**General**

Creo que debería aparecer los comandos para instalar las librerías (si eres novato no lo sabes):
! pip install netcdf4
! pip install xarray
! pip install seawater

**Argo Online School**

1. En el párrafo:

_The Argo Online school is a set of videos and hands-on jupyter notebooks to describe the minimum requiremets to use, and understand, the Argo data. You can access the content as here in a **JubyterBook**_

**JubyterBook** te lleva a la misma página ¿es correcto?

2. Directamente usando Jupyter no se accede a los archivos .nc, he necesitado descargarlos

3. Para crear el entorno no me bastó con los comandos que ponen, tuve que utilizar:
conda update --all
conda env export --no-builds > environment.yml
conda env create -f environment.yml -n AOS
conda activate AOS

Quizás es por fallo mio

4. El repositorio para descargar no existe el perfilador 6900772. Están el 6901254 (que es con el que se hacen las prácticas) y el 6901472.

5. Cambiar "Daily NOAA OI SST V2 High Resolution Dataset for **2009**:" Por **2019**

**Accessing trayectory data**

1. La librería cartopy da problemas, a mi me funcionó instalando otras librerias antes y luego cartopy instalándolo desde conda, los pasos:

- pip install proj geos
- pip install pyshp
- pip install shapely
- pip install gitpython
- Open this folder "C:\ProgramData\" and right-click on "\Anaconda3". go to properties -> security and check all the boxes for each user.
- conda install Proj
- conda install GEOS
- conda install -c conda-forge cartopy

2. La figura de la serie temporal de Accessing trayectory data sólo funciona cuando no se ha ejecutado previamente la celda que genera la figura del mapa. Si la ejecutamos después del mapa sale: 

- ValueError: Could not convert object to NumPy datetime

**Accessing argo data by float using Argopy**

1. Las gráficas de los perfiles de temperatura y practical salinity no aparece bien, cambiar por la buena

2. La última figura no está ejecutada en el book, incluirla

**Accesing Argo data by date**

Error en la 2ª celda, actualizar.

**Accessing Argo data by date using Argopy**

Vacío

**Quality Control of the Argo data**

Subir de la 6ª a la 5ª celda:
pres=dayADS.PRES    antes de      lon=dayADS.LONGITUDE+pres*0
Si no se define antes da error

**Calibrated data**

1. Añadir al repositorio para descargar el file 6900768_prof.nc

2. Añadir en la celda 4: pres=prof.PRES    Si no se añade da error al generar la gráfica

3. No sé que se quiere mostrar en la figura de la celda 5.

4. En la 8ª celda sólo se plotean los puntos azules y se corre entera. Para plotear los puntos rojos tienes que comentar la scAD

**Comment by PedroVelez** [comment]
Thanks a lot Lara, we will incorporate all the suggestions and let you know once we have a new version!

**Comment by PedroVelez** [comment]
@ldiaz-barroso thanks!, we have incorporated all the suggestions. Thanks a lot
